spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: khanimkhanim

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

  data:
    mongodb:
      host: localhost
      port: 27017
      database: library_mongodb